import random

quotes = [
 "Believe you can and you're halfway there. – Theodore Roosevelt",
    "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Dream it. Wish it. Do it.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "Success is not final; failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Act as if what you do makes a difference. It does. – William James",
    "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "Success is how high you bounce when you hit bottom. – George S. Patton",
    "The best way to predict the future is to create it. – Peter Drucker",
    "Perseverance is not a long race; it is many short races one after the other. – Walter Elliot",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "If you’re going through hell, keep going. – Winston Churchill",
    "What we fear of doing most is usually what we most need to do. – Ralph Waldo Emerson",
    "Opportunities don’t happen, you create them. – Chris Grosser",
    "The only way to achieve the impossible is to believe it is possible.",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "Go as far as you can see; when you get there, you’ll be able to see further. – Thomas Carlyle",
    "Don’t count the days, make the days count. – Muhammad Ali",
    "If you want something you’ve never had, you must be willing to do something you’ve never done. – Thomas Jefferson",
    "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "The purpose of our lives is to be happy. – Dalai Lama",
    "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
    "The only thing that can grow is the thing you give energy to. – Ralph Waldo Emerson",
    "Life isn’t about waiting for the storm to pass. It’s about learning how to dance in the rain.",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "Opportunities multiply as they are seized. – Sun Tzu",
    "Every moment is a fresh beginning. – T.S. Eliot",
    "The journey of a thousand miles begins with a single step. – Lao Tzu",
    "Believe in yourself and all that you are. – Christian D. Larson",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    # Add more quotes here
]

def get_random_quote():
    return random.choice(quotes)

if __name__ == "__main__":
    print(get_random_quote())
